### PR TITLE
build: update dependences

### PR DESCRIPTION
**Pull request by CKylinMC**
Update deps.

This PR does:
* Update deps version.
* Change `latest` to its detailed version for each dependence.(`latest` is really not a good version)

Tests:
* `--version` command not passed (not related to this pr).
* Other tests passed.

*I added a package to work with newer version of http-auth. See [http-auth#98](https://github.com/gevorg/http-auth/issues/98#issuecomment-581192063) and PR #1*

### CODE REVIEW

**Comment by andreashuber69** [comment]
Thank you for submitting this PR. As it happens, I was actually burnt by the "latest" version of the open package, which is an ESM module in its latest version (9.1.0) but was not previously (<9). This package should limit itself to major versions that it was actually tested with. Nowadays it is all to common for new major package versions to be ESM-only.

@ljcp: Please consider merging this PR. Thank you!

**Comment by CKylinMC** [comment]
> This package should limit itself to major versions that it was actually tested with.

@andreashuber69 Yes, I agree with you. But since this repo provided `package-lock.json`, I think we could install the same version of packages that the repo owner using, just remove the `node_modules` folder and run `npm ci`, not test yet but should be a solution.

**Comment by ljcp** [comment]
thank you @CKylinMC @andreashuber69

**Comment by andreashuber69** [comment]
> > This package should limit itself to major versions that it was actually tested with.
> 
> @andreashuber69 Yes, I agree with you. But since this repo provided `package-lock.json`, I think we could install the same version of packages that the repo owner using, just remove the `node_modules` folder and run `npm ci`, not test yet but should be a solution.

I set up a brand new project where I used `npm install alive-server --save-dev`  and ended up with the the version 9.1.0 of the "open" package.

You make a good point that *package-lock.json* does mention the 8.4.2 of the "open" package, but for some reason that did not matter. No idea why.

**Comment by ljcp** [comment]
@andreashuber69 going to double check this today thank you

**Pull request merged**
